name: my_shop
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.16.2 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^9.1.0
  cached_network_image: ^3.1.0
  get: ^4.6.1
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.0
  email_validator: ^2.0.1
  firebase_auth: ^3.0.2
  firebase_storage: ^10.0.4
  image_picker: ^0.8.3+3
  flutter_native_splash: ^1.3.1
  flutter_svg: ^1.0.3
  flutter_spinkit: null
  icon_badge: null
  dropdown_search: null
  timeline_tile: null
  cupertino_stepper: null
  intl: null
  shared_preferences: null
  search_page:
dev_dependencies:
  flutter_test: {sdk: flutter}
flutter_icons: {image_path_android: assets/images/logo.png, image_path_ios: assets/images/logo.png,
  android: true, ios: true, flutter_lints: ^1.0.0}
flutter:
  uses-material-design: true
  assets: [assets/fonts/, assets/icons/, assets/images/]
  fonts:
  - fonts:
    - {asset: assets/fonts/SourceSansPro.ttf}
    family: SourceSansPro
